### ISSUE TITLE
GitHub Application authentication

### ISSUE THREAD

**Issue by gmykhailiuta** [jkroepke/github_exporter#147]
Would it be possible to add a way to do [application authentication](https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps)?
Main reason is that application has a different API requests quota (15k vs 5k for personal token) so it's preferable.

**Comment by jkroepke** [comment]
The underlaying framework supports this https://octokit.github.io/rest.js/v19#authentication Maybe I have to take a look into it.

**Comment by jkroepke** [comment]
@gmykhailiuta are you able to test #148?
